version: '3.8'
services:
  # api:
  #   build:
  #     dockerfile: Dockerfile
  #     context: .
  #   volumes:
  #     - .:/app
  #     - node_modules:/app/node_modules
  #   ports:
  #     - '${STORE_PORT}:${STORE_PORT}'
  #   environment:
  #     - DATABASE_URL=${DATABASE_URL}
  #     - STORE_PORT=${STORE_PORT}
  #     - TTL_ACCESS_TOKEN=${TTL_ACCESS_TOKEN}
  #     - TTL_REFRESH_TOKEN=${TTL_REFRESH_TOKEN}
  #     - SECRET_ACCESS_TOKEN=${SECRET_ACCESS_TOKEN}
  #     - SECRET_REFRESH_TOKEN=${SECRET_REFRESH_TOKEN}
  #     - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
  #     - GOOGLE_SECRET=${GOOGLE_SECRET}
  #   restart: unless-stopped
  #   depends_on:
  #     - db
  db:
    image: mysql
    restart: unless-stopped
    volumes:
      - ./public/db:/var/lib/mysql
      - ./divine_db.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=divine_db
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  redis:
    image: redis
    restart: always
    volumes:
      - ./public/redis:/data
    ports:
      - 6379:6379
volumes:
  node_modules:
