version: '3.8'
services:
  api:
    image: chauvanloc/divine-be
    ports:
      - 1234:1234
    environment:
      - HOST_STORE=18.141.160.212
      - REDIS_HOST_STORE=redis
      - DATABASE_URL=mysql://alo:alo@my-store-db.cy0uyyfcljw9.ap-southeast-1.rds.amazonaws.com:3306/divine_store?schema=public
      - STORE_PORT=1234
      - SECRET_ACCESS_TOKEN="SECRET_ACCESS_TOKEN"
      - SECRET_REFRESH_TOKEN="SECRET_REFRESH_TOKEN"
      - GOOGLE_CLIENT_ID="408781403808-1hma7js2tiihc45cajh20vor36ooec34.apps.googleusercontent.com"
      - GOOGLE_SECRET="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"
      - LIMIT_STORE=12
      - MAIL_HOST=smtp.gmail.com
      - MAIL_USER=locchau.220401@gmail.com
      - MAIL_PASSWORD=kcsaltzzvdupltxh
      - MAIL_FROM=locchau.220401@gmail.com
      - MAIL_TRANSPORT=smtp://locchau.220401@gmail.com:kcsaltzzvdupltxh@smtp.gmail.com
    restart: unless-stopped
    depends_on:
      - redis
  redis:
    image: redis
    restart: always
    volumes:
      - ./public/redis:/data
    ports:
      - 6379:6379
volumes:
  node_modules:
